# Generated by Django 4.2.6 on 2023-10-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
