# Generated by Django 4.2.6 on 2023-10-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.post'),
        ),
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
