# Generated by Django 4.2.7 on 2023-11-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='foreign_author_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_foreign',
        ),
        migrations.AddField(
            model_name='like',
            name='author_endpoint',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
