# Generated by Django 4.2.7 on 2023-11-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="follows",
        ),
        migrations.RemoveField(
            model_name="author",
            name="friends",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="foreign_author_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_foreign",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="followee",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="foreign_follower_id",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="is_foreign",
        ),
        migrations.RemoveField(
            model_name="like",
            name="foreign_author_id",
        ),
        migrations.RemoveField(
            model_name="like",
            name="is_foreign",
        ),
        migrations.AddField(
            model_name="follower",
            name="followee_endpoint",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="follower",
            name="follower_endpoint",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
    ]
