# Generated by Django 4.2.6 on 2023-11-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="private_to",
        ),
    ]
