# Generated by Django 4.2.7 on 2023-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="author_data",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="post",
            name="author_data",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="post",
            name="author_endpoint",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
