# Generated by Django 4.2.7 on 2023-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_like_author_remove_like_foreign_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment_endpoint',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_endpoint',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
