# Generated by Django 4.2.7 on 2023-11-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_follower_followee_host_follower_follower_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="followee_data",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="follower",
            name="follower_data",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
