# Generated by Django 4.2.6 on 2023-10-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_follower_follow_author_github_and_more'),
        ('main', '0003_alter_author_updated_at_alter_comment_updated_at_and_more'),
    ]

    operations = [
    ]
