# Generated by Django 4.2.7 on 2023-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="author",
        ),
        migrations.AddField(
            model_name="inbox",
            name="author_id",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
