# Generated by Django 4.2.6 on 2023-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_follow_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
