# Generated by Django 4.2.6 on 2023-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_follow_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
