# Generated by Django 4.2.6 on 2023-11-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_post_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
