# Generated by Django 4.2.6 on 2023-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_categories_post_contenttype_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default title', max_length=200),
        ),
    ]
