# Generated by Django 4.2.6 on 2023-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_follower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
