# Generated by Django 4.2.6 on 2023-11-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
