# Generated by Django 4.2.6 on 2023-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_follower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='friendship',
            field=models.BooleanField(default=False),
        ),
    ]
