# Generated by Django 4.2.6 on 2023-11-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_author_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("auto_permit_users", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="is_permitted",
            field=models.BooleanField(default=True),
        ),
    ]
