# Generated by Django 4.2.6 on 2023-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_serversettings_author_is_permitted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="github",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="profileImage",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
