# Generated by Django 4.2.6 on 2023-11-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_post_title"),
        ("main", "0010_alter_author_github_alter_author_profileimage"),
    ]

    operations = []
