# Generated by Django 4.2.6 on 2023-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_merge_20231122_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
