# Generated by Django 4.2.6 on 2023-11-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="unlisted",
            field=models.BooleanField(default=False),
        ),
    ]
